<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class AdsGroup extends Model
{
    use HasFactory;
    protected $fillable = [
        'pacing',
        'deep_bid_type',
        'modify_time',
        'spending_power',
        'budget',
        'schedule_infos',
        'keywords',
        'advertiser_id',
        'purchase_intention_keyword_ids',
        'creative_material_mode',
        'app_download_url',
        'actions',
        'auto_targeting_enabled',
        'promotion_website_type',
        'languages',
        'promotion_type',
        'schedule_start_time',
        'frequency_schedule',
        'skip_learning_phase',
        'household_income',
        'optimization_goal',
        'pixel_id',
        'conversion_bid_price',
        'schedule_type',
        'adgroup_app_profile_page_state',
        'excluded_custom_actions',
        'isp_ids',
        'operation_status',
        'schedule_end_time',
        'inventory_filter_enabled',
        'deep_cpa_bid',
        'category_exclusion_ids',
        'feed_type',
        'device_model_ids',
        'rf_purchased_type',
        'conversion_window',
        'purchased_reach',
        'operating_systems',
        'brand_safety_partner',
        'dayparting',
        'adgroup_id',
        'audience_ids',
        'campaign_name',
        'is_smart_performance_campaign',
        'is_hfss',
        'device_price_ranges',
        'gender',
        'rf_estimated_frequency',
        'campaign_id',
        'delivery_mode',
        'network_types',
        'share_disabled',
        'budget_mode',
        'rf_estimated_cpr',
        'placements',
        'video_download_disabled',
        'billing_event',
        'statistic_type',
        'frequency',
        'category_id',
        'scheduled_budget',
        'zipcode_ids',
        'search_result_enabled',
        'adgroup_name',
        'placement_type',
        'contextual_tag_ids',
        'next_day_retention',
        'targeting_expansion',
        'create_time',
        'secondary_status',
        'purchased_impression',
        'comment_disabled',
        'app_id',
        'interest_category_ids',
        'age_groups',
        'brand_safety_type',
        'optimization_event',
        'interest_keyword_ids',
        'bid_display_mode',
        'bid_price',
        'excluded_audience_ids',
        'secondary_optimization_event',
        'is_new_structure',
        'location_ids',
        'included_custom_actions',
        'bid_type',
        'app_type',
        'ios14_quota_type',
    ];

}
